Yarn 2, webpack 5.
single-spa/standalone-single-spa-webpack-plugin pull request #5
Opened 2020-11-28 01:30 UTC by joeldenning

In webpack 4, you specify webpack env vars via `--env.varName`. In webpack 5, it's `--env varName`. This change updates the language in the html file to be correct depending on which version of webpack you're using. I also added yarn 2

2020-11-28 12:47 UTC, merceyz requested changes
Hey, I saw [the thread on twitter](https://mobile.twitter.com/Joelbdenning/status/1332440439496998913) and started working on PnP support for `single-spa` and was about to make a PR here but since you're already on it i'll leave my findings here. 

The use of `safe-require` breaks PnP support (and makes you rely on hoisting when using node_modules) because it runs the require on behalf of itself and not the caller https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies and should be replaced with a simple require wrapped in `try catch`

2020-11-28 12:47 UTC, merceyz commented on lib/standalone-single-spa.js
> +const HtmlWebpackPlugin = safeRequire("html-webpack-plugin");
Could you try removing it and just using normal require with a try catch?

2020-11-28 12:47 UTC, merceyz commented on lib/standalone-single-spa.js
> +  isWebpack5 = safeRequire("webpack").version.startsWith("5");
Needs to be a peer dependency (and not using safeRequire)

2020-11-28 19:14 UTC, joeldenning commented
Thanks for your review - i didn't know that about safeRequire. Will update.

2020-11-29 07:55 UTC, joeldenning commented
I've updated this with your feedback.

2020-11-29 11:33 UTC, merceyz approved these changes
Perfect, looks good!

2020-11-29 19:06 UTC, merged